services:
  nutshell:
    image: cashubtc/nutshell:0.16.4
    container_name: nutshell
    ports:
      - "3338:3338"
    environment:
      MINT_LIGHTNING_BACKEND: FakeWallet
      MINT_INPUT_FEE_PPK: 0
      MINT_LISTEN_HOST: 0.0.0.0
      MINT_LISTEN_PORT: 3338
      MINT_PRIVATE_KEY: TEST_PRIVATE_KEY_OHH_YEAH_BABY
    command: poetry run mint