version: '3.8'

services:
  nutshell:
    image: cashubtc/nutshell:0.16.4
    container_name: nutshell
    ports:
      - "3338:3338"
    environment:
      MINT_LIGHTNING_BACKEND: FakeWallet
      MINT_INPUT_FEE_PPK: 0
      MINT_LISTEN_HOST: 0.0.0.0
      MINT_LISTEN_PORT: 3338
      MINT_PRIVATE_KEY: TEST_PRIVATE_KEY_OHH_YEAH_BABY
    command: poetry run mint
    networks:
      - postgres-network
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openpleb-backend
    restart: unless-stopped
    environment:
      PORT: 3003
      DB_FILE_NAME: /app/data/local.db
      LOG_FILE_NAME: /app/data/logs/app.log
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      CASHU_SEED_PHRASE: because oxygen subway review excuse elder coconut kingdom govern scrub enact minimum
      FRONTEND_URL: http://frontend:3000
      OPENPLEB_PLATFORM_FEE_PERCENTAGE: 0
      OPENPLEB_PLATFORM_FEE_FLAT_RATE: 100
      OPENPLEB_TAKER_FEE_PERCENTAGE: 2
      OPENPLEB_TAKER_FEE_FLAT_RATE: 100
      OPENPLEB_BOND_PERCENTAGE: 10
      OPENPLEB_BOND_FLAT_RATE: 500
      OPENPLEB_CURRENCY: KRW
      OPENPLEB_MINT_URL: http://nutshell:3338
      OPENPLEB_MAX_FIAT_AMOUNT: 100000
    ports:
      - "3003:3003"
    volumes:
      - backend-data:/app/data
    networks:
      - postgres-network
    depends_on:
      - postgres
      - nutshell

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: openpleb-frontend
    restart: unless-stopped
    environment:
      PUBLIC_BACKEND_URL: http://localhost:3003
      PUBLIC_API_VERSION: v1
    ports:
      - "3000:3000"
    networks:
      - postgres-network
    depends_on:
      - backend
      
  postgres:
    image: postgres:15.3
    container_name: my-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Uncomment if you want to mount initialization scripts
      # - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
volumes:
  postgres-data:
    driver: local
  backend-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
